### ISSUE TITLE
Improved polish translation to New World Cities

### ISSUE THREAD

**Issue by Bzhydack** [jakobharder/anno1800-jakobs-mods#104]
I noticed there are some errors in polish translations, so I corrected them.
Also, is possible to make translated banner when "New milestone" is reached? I mean, I can change it directly, in Banner file, but after every update I will have too do this again.[
[[Addon] New World Cities (Jakob).zip](https://github.com/jakobharder/anno1800-jakobs-mods/files/14482505/Addon.New.World.Cities.Jakob.zip)
](url)

**Comment by jakobharder** [comment]
Thanks, I'll add it to the update I'm working on.
