### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by mechanicFS** [jakobharder/anno1800-jakobs-mods#80]
Hi! Constant errors, although all mods and files are installed.
![2023-06-06 15-47-51 Скриншот экрана](https://github.com/jakobharder/anno1800-jakobs-mods/assets/76490045/abcfc67a-47b0-4cad-bfe4-242f4f3df91c)

**Comment by jakobharder** [comment]
You downloaded the source code.

You need to download the [release](https://github.com/jakobharder/anno-1800-jakobs-mods/releases).
