### ISSUE TITLE
Small Power Plants missing

### ISSUE THREAD

**Issue by Sebbl96** [jakobharder/anno1800-jakobs-mods#82]
When I update the mod packages and load my old game it tells me there are some new mods and some mods missing. so far so good. 

It also tells me about the new [Addon] Industrial Cities which now should include the small Power Plants. 
But as the game finished loading, all of my small Power Plants dissapeared and I can't build new ones.

There are other mods of the [AddOn] Package working as far as I can see. (For example the modular factories)

Is there maybe something obvious I forgot/did wrong?

**Comment by jakobharder** [comment]
That's my fault. Thanks for the report.

The new release fixes that:
https://github.com/jakobharder/anno1800-jakobs-mods/releases/download/v5.9.3/Industrial-Cities-3.0.4.zip
