### ISSUE TITLE
Issues with 'Alternative Needs' in Multiplayer

### ISSUE THREAD

**Issue by Mulleboy** [jakobharder/anno1800-jakobs-mods#84]
Me and my partner were playing your mod in a regular, build focused MP game and noticed halfway through that the non-host player does not have the Alternative Needs buff on residences, and therefor cannot benefit from the Alternative Needs mod.

I noticed that in the recent changelog it said it should work for Multiplayer.
We tried disabling all mods besides the ones in your collection, all managed via iModYourAnno.

To test it out we tried switching host by creating a new lobby, that's how we found out only the host was granted the buff on residences.

**Comment by jakobharder** [comment]
The global buffs are a bit wonky in multiplayer.

You may be able to heal the problem going to another session and then back.

The buff is re-checked with every session change.

**Comment by jakobharder** [comment]
I did some changes in the reason version that may help.

**Comment by MarvinDrude** [comment]
For me its still no effect for my friend when i host the game. I have the effect, he does not. We upgraded to the latest version.

**Comment by jakobharder** [comment]
I uploaded an updated version that seems to work for me:
https://mod.io/g/anno-1800/m/jakob-alternative-needs

**Comment by MarvinDrude** [comment]
We tested it but for us it didn't work. But it could be very well the case that its due to us only having islands on 2 extra modded sessions at this current time. So I can't speak for the case of just vanilla sessions being played.
It is not that urgent anyway because my friend just building the normal stuff for the normal residences.

**Comment by arcalys** [comment]
For us it does not work either on a newly created multiplayer game. I get the "alternative needs" buff but the other player does not. Also, none of us gets the production chains, and we can't produce said needs, they don't even appear. We thought it could be related to a conflict with another mod, so we disabled everything and launched a new game with just "Alternative needs", "Industrial cities" and "Pescatarians", but nothing still.

**Comment by Mulleboy** [comment]
Just tried today with latest GU and mod, still doesn't affect the 2nd player unfortunately. Perhaps a building with max island coverage to act as a "beacon" for the Alternative Needs modifier?
